app = "furmannowscrapers"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[processes]
  app = "gunicorn backend.main:app -b 0.0.0.0:8080"
  cron = "cron -f"

[http_service]
  internal_port = 8080
  force_https = true
  processes = ["app"]

